/* AutoGenerated Code, changes may be overwritten
* INPUT GRAMMAR:
* globals := {value={varDecl | func} {ws+ | '$'}}*
* mutable := 'let'
* constant := 'const'
* varDecl := ws* mutability={ constant | mutable } ws+ name=name ws* equals ws* value=expression
* name := name='[a-zA-Z]+\w*'
* equals := '='
* ws := '\s'
* obj := '\{' ws* fields=fields ws* '\}'
* str := '\'' value='[\w \t]*' '\''
* bool := value={'true' | 'false'}
* num := value='-?\d+(\.\d+)?'
* literal := obj | str | bool | num
* newLineOrComma := '\n|,'
* field := name=name ws* ':' value=literal newLineOrComma?
* fields := value=field*
* space := ' '
* executable := ws* value={value={ret | varDecl | assignment | expression } ws+ }*
* expression := !ret root={literal | name   } methods={method}*
* method := method={parameterIndex | literalIndex}
* parameterIndex := '\[' space* value={expression} space* '\]'
* literalIndex := '\.' value={name}
* objectIndex := obj=expression index={parameterIndex | literalIndex}
* ret := 'return(?=\s)' space* value={'(?<= )' exp=expression}?
* func := ws* 'public' space+ 'function' space+ name=name space* args=args ws* '\{' body=executable '\}'
* args := '\(' ws* leadingArgs={name=name newLineOrComma ws*}* ws* lastArg={name}? ws* '\)'
* assignment := target=expression space* equals space* value=expression
*/
type Nullable<T> = T | null;
type $$RuleType<T> = (log?: (msg: string) => void) => Nullable<T>;
export interface ContextRecorder {
    record(pos: PosInfo, depth: number, result: any, negating: boolean, extraInfo: string[]): void;
}
interface ASTNodeIntf {
    kind: ASTKinds;
}
export enum ASTKinds {
    globals = "globals",
    globals_$0 = "globals_$0",
    globals_$0_$0_1 = "globals_$0_$0_1",
    globals_$0_$0_2 = "globals_$0_$0_2",
    globals_$0_$1_1 = "globals_$0_$1_1",
    globals_$0_$1_2 = "globals_$0_$1_2",
    mutable = "mutable",
    constant = "constant",
    varDecl = "varDecl",
    varDecl_$0_1 = "varDecl_$0_1",
    varDecl_$0_2 = "varDecl_$0_2",
    name = "name",
    equals = "equals",
    ws = "ws",
    obj = "obj",
    str = "str",
    bool = "bool",
    bool_$0_1 = "bool_$0_1",
    bool_$0_2 = "bool_$0_2",
    num = "num",
    literal_1 = "literal_1",
    literal_2 = "literal_2",
    literal_3 = "literal_3",
    literal_4 = "literal_4",
    newLineOrComma = "newLineOrComma",
    field = "field",
    fields = "fields",
    space = "space",
    executable = "executable",
    executable_$0 = "executable_$0",
    executable_$0_$0_1 = "executable_$0_$0_1",
    executable_$0_$0_2 = "executable_$0_$0_2",
    executable_$0_$0_3 = "executable_$0_$0_3",
    executable_$0_$0_4 = "executable_$0_$0_4",
    expression = "expression",
    expression_$0_1 = "expression_$0_1",
    expression_$0_2 = "expression_$0_2",
    expression_$1 = "expression_$1",
    method = "method",
    method_$0_1 = "method_$0_1",
    method_$0_2 = "method_$0_2",
    parameterIndex = "parameterIndex",
    parameterIndex_$0 = "parameterIndex_$0",
    literalIndex = "literalIndex",
    literalIndex_$0 = "literalIndex_$0",
    objectIndex = "objectIndex",
    objectIndex_$0_1 = "objectIndex_$0_1",
    objectIndex_$0_2 = "objectIndex_$0_2",
    ret = "ret",
    ret_$0 = "ret_$0",
    func = "func",
    args = "args",
    args_$0 = "args_$0",
    args_$1 = "args_$1",
    assignment = "assignment",
}
export type globals = globals_$0[];
export interface globals_$0 {
    kind: ASTKinds.globals_$0;
    value: globals_$0_$0;
}
export type globals_$0_$0 = globals_$0_$0_1 | globals_$0_$0_2;
export type globals_$0_$0_1 = varDecl;
export type globals_$0_$0_2 = func;
export type globals_$0_$1 = globals_$0_$1_1 | globals_$0_$1_2;
export type globals_$0_$1_1 = ws[];
export type globals_$0_$1_2 = string;
export type mutable = string;
export type constant = string;
export interface varDecl {
    kind: ASTKinds.varDecl;
    mutability: varDecl_$0;
    name: name;
    value: expression;
}
export type varDecl_$0 = varDecl_$0_1 | varDecl_$0_2;
export type varDecl_$0_1 = constant;
export type varDecl_$0_2 = mutable;
export interface name {
    kind: ASTKinds.name;
    name: string;
}
export type equals = string;
export type ws = string;
export interface obj {
    kind: ASTKinds.obj;
    fields: fields;
}
export interface str {
    kind: ASTKinds.str;
    value: string;
}
export interface bool {
    kind: ASTKinds.bool;
    value: bool_$0;
}
export type bool_$0 = bool_$0_1 | bool_$0_2;
export type bool_$0_1 = string;
export type bool_$0_2 = string;
export interface num {
    kind: ASTKinds.num;
    value: string;
}
export type literal = literal_1 | literal_2 | literal_3 | literal_4;
export type literal_1 = obj;
export type literal_2 = str;
export type literal_3 = bool;
export type literal_4 = num;
export type newLineOrComma = string;
export interface field {
    kind: ASTKinds.field;
    name: name;
    value: literal;
}
export interface fields {
    kind: ASTKinds.fields;
    value: field[];
}
export type space = string;
export interface executable {
    kind: ASTKinds.executable;
    value: executable_$0[];
}
export interface executable_$0 {
    kind: ASTKinds.executable_$0;
    value: executable_$0_$0;
}
export type executable_$0_$0 = executable_$0_$0_1 | executable_$0_$0_2 | executable_$0_$0_3 | executable_$0_$0_4;
export type executable_$0_$0_1 = ret;
export type executable_$0_$0_2 = varDecl;
export type executable_$0_$0_3 = assignment;
export type executable_$0_$0_4 = expression;
export interface expression {
    kind: ASTKinds.expression;
    root: expression_$0;
    methods: expression_$1[];
}
export type expression_$0 = expression_$0_1 | expression_$0_2;
export type expression_$0_1 = literal;
export type expression_$0_2 = name;
export type expression_$1 = method;
export interface method {
    kind: ASTKinds.method;
    method: method_$0;
}
export type method_$0 = method_$0_1 | method_$0_2;
export type method_$0_1 = parameterIndex;
export type method_$0_2 = literalIndex;
export interface parameterIndex {
    kind: ASTKinds.parameterIndex;
    value: parameterIndex_$0;
}
export type parameterIndex_$0 = expression;
export interface literalIndex {
    kind: ASTKinds.literalIndex;
    value: literalIndex_$0;
}
export type literalIndex_$0 = name;
export interface objectIndex {
    kind: ASTKinds.objectIndex;
    obj: expression;
    index: objectIndex_$0;
}
export type objectIndex_$0 = objectIndex_$0_1 | objectIndex_$0_2;
export type objectIndex_$0_1 = parameterIndex;
export type objectIndex_$0_2 = literalIndex;
export interface ret {
    kind: ASTKinds.ret;
    value: Nullable<ret_$0>;
}
export interface ret_$0 {
    kind: ASTKinds.ret_$0;
    exp: expression;
}
export interface func {
    kind: ASTKinds.func;
    name: name;
    args: args;
    body: executable;
}
export interface args {
    kind: ASTKinds.args;
    leadingArgs: args_$0[];
    lastArg: Nullable<args_$1>;
}
export interface args_$0 {
    kind: ASTKinds.args_$0;
    name: name;
}
export type args_$1 = name;
export interface assignment {
    kind: ASTKinds.assignment;
    target: expression;
    value: expression;
}
export class Parser {
    private readonly input: string;
    private pos: PosInfo;
    private negating: boolean = false;
    constructor(input: string) {
        this.pos = {overallPos: 0, line: 1, offset: 0};
        this.input = input;
    }
    public reset(pos: PosInfo) {
        this.pos = pos;
    }
    public finished(): boolean {
        return this.pos.overallPos === this.input.length;
    }
    public matchglobals($$dpth: number, $$cr?: ContextRecorder): Nullable<globals> {
        return this.loop<globals_$0>(() => this.matchglobals_$0($$dpth + 1, $$cr), true);
    }
    public matchglobals_$0($$dpth: number, $$cr?: ContextRecorder): Nullable<globals_$0> {
        return this.runner<globals_$0>($$dpth,
            (log) => {
                if (log) {
                    log("globals_$0");
                }
                let $scope$value: Nullable<globals_$0_$0>;
                let $$res: Nullable<globals_$0> = null;
                if (true
                    && ($scope$value = this.matchglobals_$0_$0($$dpth + 1, $$cr)) !== null
                    && this.matchglobals_$0_$1($$dpth + 1, $$cr) !== null
                ) {
                    $$res = {kind: ASTKinds.globals_$0, value: $scope$value};
                }
                return $$res;
            }, $$cr)();
    }
    public matchglobals_$0_$0($$dpth: number, $$cr?: ContextRecorder): Nullable<globals_$0_$0> {
        return this.choice<globals_$0_$0>([
            () => this.matchglobals_$0_$0_1($$dpth + 1, $$cr),
            () => this.matchglobals_$0_$0_2($$dpth + 1, $$cr),
        ]);
    }
    public matchglobals_$0_$0_1($$dpth: number, $$cr?: ContextRecorder): Nullable<globals_$0_$0_1> {
        return this.matchvarDecl($$dpth + 1, $$cr);
    }
    public matchglobals_$0_$0_2($$dpth: number, $$cr?: ContextRecorder): Nullable<globals_$0_$0_2> {
        return this.matchfunc($$dpth + 1, $$cr);
    }
    public matchglobals_$0_$1($$dpth: number, $$cr?: ContextRecorder): Nullable<globals_$0_$1> {
        return this.choice<globals_$0_$1>([
            () => this.matchglobals_$0_$1_1($$dpth + 1, $$cr),
            () => this.matchglobals_$0_$1_2($$dpth + 1, $$cr),
        ]);
    }
    public matchglobals_$0_$1_1($$dpth: number, $$cr?: ContextRecorder): Nullable<globals_$0_$1_1> {
        return this.loop<ws>(() => this.matchws($$dpth + 1, $$cr), false);
    }
    public matchglobals_$0_$1_2($$dpth: number, $$cr?: ContextRecorder): Nullable<globals_$0_$1_2> {
        return this.regexAccept(String.raw`(?:$)`, $$dpth + 1, $$cr);
    }
    public matchmutable($$dpth: number, $$cr?: ContextRecorder): Nullable<mutable> {
        return this.regexAccept(String.raw`(?:let)`, $$dpth + 1, $$cr);
    }
    public matchconstant($$dpth: number, $$cr?: ContextRecorder): Nullable<constant> {
        return this.regexAccept(String.raw`(?:const)`, $$dpth + 1, $$cr);
    }
    public matchvarDecl($$dpth: number, $$cr?: ContextRecorder): Nullable<varDecl> {
        return this.runner<varDecl>($$dpth,
            (log) => {
                if (log) {
                    log("varDecl");
                }
                let $scope$mutability: Nullable<varDecl_$0>;
                let $scope$name: Nullable<name>;
                let $scope$value: Nullable<expression>;
                let $$res: Nullable<varDecl> = null;
                if (true
                    && this.loop<ws>(() => this.matchws($$dpth + 1, $$cr), true) !== null
                    && ($scope$mutability = this.matchvarDecl_$0($$dpth + 1, $$cr)) !== null
                    && this.loop<ws>(() => this.matchws($$dpth + 1, $$cr), false) !== null
                    && ($scope$name = this.matchname($$dpth + 1, $$cr)) !== null
                    && this.loop<ws>(() => this.matchws($$dpth + 1, $$cr), true) !== null
                    && this.matchequals($$dpth + 1, $$cr) !== null
                    && this.loop<ws>(() => this.matchws($$dpth + 1, $$cr), true) !== null
                    && ($scope$value = this.matchexpression($$dpth + 1, $$cr)) !== null
                ) {
                    $$res = {kind: ASTKinds.varDecl, mutability: $scope$mutability, name: $scope$name, value: $scope$value};
                }
                return $$res;
            }, $$cr)();
    }
    public matchvarDecl_$0($$dpth: number, $$cr?: ContextRecorder): Nullable<varDecl_$0> {
        return this.choice<varDecl_$0>([
            () => this.matchvarDecl_$0_1($$dpth + 1, $$cr),
            () => this.matchvarDecl_$0_2($$dpth + 1, $$cr),
        ]);
    }
    public matchvarDecl_$0_1($$dpth: number, $$cr?: ContextRecorder): Nullable<varDecl_$0_1> {
        return this.matchconstant($$dpth + 1, $$cr);
    }
    public matchvarDecl_$0_2($$dpth: number, $$cr?: ContextRecorder): Nullable<varDecl_$0_2> {
        return this.matchmutable($$dpth + 1, $$cr);
    }
    public matchname($$dpth: number, $$cr?: ContextRecorder): Nullable<name> {
        return this.runner<name>($$dpth,
            (log) => {
                if (log) {
                    log("name");
                }
                let $scope$name: Nullable<string>;
                let $$res: Nullable<name> = null;
                if (true
                    && ($scope$name = this.regexAccept(String.raw`(?:[a-zA-Z]+\w*)`, $$dpth + 1, $$cr)) !== null
                ) {
                    $$res = {kind: ASTKinds.name, name: $scope$name};
                }
                return $$res;
            }, $$cr)();
    }
    public matchequals($$dpth: number, $$cr?: ContextRecorder): Nullable<equals> {
        return this.regexAccept(String.raw`(?:=)`, $$dpth + 1, $$cr);
    }
    public matchws($$dpth: number, $$cr?: ContextRecorder): Nullable<ws> {
        return this.regexAccept(String.raw`(?:\s)`, $$dpth + 1, $$cr);
    }
    public matchobj($$dpth: number, $$cr?: ContextRecorder): Nullable<obj> {
        return this.runner<obj>($$dpth,
            (log) => {
                if (log) {
                    log("obj");
                }
                let $scope$fields: Nullable<fields>;
                let $$res: Nullable<obj> = null;
                if (true
                    && this.regexAccept(String.raw`(?:\{)`, $$dpth + 1, $$cr) !== null
                    && this.loop<ws>(() => this.matchws($$dpth + 1, $$cr), true) !== null
                    && ($scope$fields = this.matchfields($$dpth + 1, $$cr)) !== null
                    && this.loop<ws>(() => this.matchws($$dpth + 1, $$cr), true) !== null
                    && this.regexAccept(String.raw`(?:\})`, $$dpth + 1, $$cr) !== null
                ) {
                    $$res = {kind: ASTKinds.obj, fields: $scope$fields};
                }
                return $$res;
            }, $$cr)();
    }
    public matchstr($$dpth: number, $$cr?: ContextRecorder): Nullable<str> {
        return this.runner<str>($$dpth,
            (log) => {
                if (log) {
                    log("str");
                }
                let $scope$value: Nullable<string>;
                let $$res: Nullable<str> = null;
                if (true
                    && this.regexAccept(String.raw`(?:\')`, $$dpth + 1, $$cr) !== null
                    && ($scope$value = this.regexAccept(String.raw`(?:[\w \t]*)`, $$dpth + 1, $$cr)) !== null
                    && this.regexAccept(String.raw`(?:\')`, $$dpth + 1, $$cr) !== null
                ) {
                    $$res = {kind: ASTKinds.str, value: $scope$value};
                }
                return $$res;
            }, $$cr)();
    }
    public matchbool($$dpth: number, $$cr?: ContextRecorder): Nullable<bool> {
        return this.runner<bool>($$dpth,
            (log) => {
                if (log) {
                    log("bool");
                }
                let $scope$value: Nullable<bool_$0>;
                let $$res: Nullable<bool> = null;
                if (true
                    && ($scope$value = this.matchbool_$0($$dpth + 1, $$cr)) !== null
                ) {
                    $$res = {kind: ASTKinds.bool, value: $scope$value};
                }
                return $$res;
            }, $$cr)();
    }
    public matchbool_$0($$dpth: number, $$cr?: ContextRecorder): Nullable<bool_$0> {
        return this.choice<bool_$0>([
            () => this.matchbool_$0_1($$dpth + 1, $$cr),
            () => this.matchbool_$0_2($$dpth + 1, $$cr),
        ]);
    }
    public matchbool_$0_1($$dpth: number, $$cr?: ContextRecorder): Nullable<bool_$0_1> {
        return this.regexAccept(String.raw`(?:true)`, $$dpth + 1, $$cr);
    }
    public matchbool_$0_2($$dpth: number, $$cr?: ContextRecorder): Nullable<bool_$0_2> {
        return this.regexAccept(String.raw`(?:false)`, $$dpth + 1, $$cr);
    }
    public matchnum($$dpth: number, $$cr?: ContextRecorder): Nullable<num> {
        return this.runner<num>($$dpth,
            (log) => {
                if (log) {
                    log("num");
                }
                let $scope$value: Nullable<string>;
                let $$res: Nullable<num> = null;
                if (true
                    && ($scope$value = this.regexAccept(String.raw`(?:-?\d+(\.\d+)?)`, $$dpth + 1, $$cr)) !== null
                ) {
                    $$res = {kind: ASTKinds.num, value: $scope$value};
                }
                return $$res;
            }, $$cr)();
    }
    public matchliteral($$dpth: number, $$cr?: ContextRecorder): Nullable<literal> {
        return this.choice<literal>([
            () => this.matchliteral_1($$dpth + 1, $$cr),
            () => this.matchliteral_2($$dpth + 1, $$cr),
            () => this.matchliteral_3($$dpth + 1, $$cr),
            () => this.matchliteral_4($$dpth + 1, $$cr),
        ]);
    }
    public matchliteral_1($$dpth: number, $$cr?: ContextRecorder): Nullable<literal_1> {
        return this.matchobj($$dpth + 1, $$cr);
    }
    public matchliteral_2($$dpth: number, $$cr?: ContextRecorder): Nullable<literal_2> {
        return this.matchstr($$dpth + 1, $$cr);
    }
    public matchliteral_3($$dpth: number, $$cr?: ContextRecorder): Nullable<literal_3> {
        return this.matchbool($$dpth + 1, $$cr);
    }
    public matchliteral_4($$dpth: number, $$cr?: ContextRecorder): Nullable<literal_4> {
        return this.matchnum($$dpth + 1, $$cr);
    }
    public matchnewLineOrComma($$dpth: number, $$cr?: ContextRecorder): Nullable<newLineOrComma> {
        return this.regexAccept(String.raw`(?:\n|,)`, $$dpth + 1, $$cr);
    }
    public matchfield($$dpth: number, $$cr?: ContextRecorder): Nullable<field> {
        return this.runner<field>($$dpth,
            (log) => {
                if (log) {
                    log("field");
                }
                let $scope$name: Nullable<name>;
                let $scope$value: Nullable<literal>;
                let $$res: Nullable<field> = null;
                if (true
                    && ($scope$name = this.matchname($$dpth + 1, $$cr)) !== null
                    && this.loop<ws>(() => this.matchws($$dpth + 1, $$cr), true) !== null
                    && this.regexAccept(String.raw`(?::)`, $$dpth + 1, $$cr) !== null
                    && ($scope$value = this.matchliteral($$dpth + 1, $$cr)) !== null
                    && ((this.matchnewLineOrComma($$dpth + 1, $$cr)) || true)
                ) {
                    $$res = {kind: ASTKinds.field, name: $scope$name, value: $scope$value};
                }
                return $$res;
            }, $$cr)();
    }
    public matchfields($$dpth: number, $$cr?: ContextRecorder): Nullable<fields> {
        return this.runner<fields>($$dpth,
            (log) => {
                if (log) {
                    log("fields");
                }
                let $scope$value: Nullable<field[]>;
                let $$res: Nullable<fields> = null;
                if (true
                    && ($scope$value = this.loop<field>(() => this.matchfield($$dpth + 1, $$cr), true)) !== null
                ) {
                    $$res = {kind: ASTKinds.fields, value: $scope$value};
                }
                return $$res;
            }, $$cr)();
    }
    public matchspace($$dpth: number, $$cr?: ContextRecorder): Nullable<space> {
        return this.regexAccept(String.raw`(?: )`, $$dpth + 1, $$cr);
    }
    public matchexecutable($$dpth: number, $$cr?: ContextRecorder): Nullable<executable> {
        return this.runner<executable>($$dpth,
            (log) => {
                if (log) {
                    log("executable");
                }
                let $scope$value: Nullable<executable_$0[]>;
                let $$res: Nullable<executable> = null;
                if (true
                    && this.loop<ws>(() => this.matchws($$dpth + 1, $$cr), true) !== null
                    && ($scope$value = this.loop<executable_$0>(() => this.matchexecutable_$0($$dpth + 1, $$cr), true)) !== null
                ) {
                    $$res = {kind: ASTKinds.executable, value: $scope$value};
                }
                return $$res;
            }, $$cr)();
    }
    public matchexecutable_$0($$dpth: number, $$cr?: ContextRecorder): Nullable<executable_$0> {
        return this.runner<executable_$0>($$dpth,
            (log) => {
                if (log) {
                    log("executable_$0");
                }
                let $scope$value: Nullable<executable_$0_$0>;
                let $$res: Nullable<executable_$0> = null;
                if (true
                    && ($scope$value = this.matchexecutable_$0_$0($$dpth + 1, $$cr)) !== null
                    && this.loop<ws>(() => this.matchws($$dpth + 1, $$cr), false) !== null
                ) {
                    $$res = {kind: ASTKinds.executable_$0, value: $scope$value};
                }
                return $$res;
            }, $$cr)();
    }
    public matchexecutable_$0_$0($$dpth: number, $$cr?: ContextRecorder): Nullable<executable_$0_$0> {
        return this.choice<executable_$0_$0>([
            () => this.matchexecutable_$0_$0_1($$dpth + 1, $$cr),
            () => this.matchexecutable_$0_$0_2($$dpth + 1, $$cr),
            () => this.matchexecutable_$0_$0_3($$dpth + 1, $$cr),
            () => this.matchexecutable_$0_$0_4($$dpth + 1, $$cr),
        ]);
    }
    public matchexecutable_$0_$0_1($$dpth: number, $$cr?: ContextRecorder): Nullable<executable_$0_$0_1> {
        return this.matchret($$dpth + 1, $$cr);
    }
    public matchexecutable_$0_$0_2($$dpth: number, $$cr?: ContextRecorder): Nullable<executable_$0_$0_2> {
        return this.matchvarDecl($$dpth + 1, $$cr);
    }
    public matchexecutable_$0_$0_3($$dpth: number, $$cr?: ContextRecorder): Nullable<executable_$0_$0_3> {
        return this.matchassignment($$dpth + 1, $$cr);
    }
    public matchexecutable_$0_$0_4($$dpth: number, $$cr?: ContextRecorder): Nullable<executable_$0_$0_4> {
        return this.matchexpression($$dpth + 1, $$cr);
    }
    public matchexpression($$dpth: number, $$cr?: ContextRecorder): Nullable<expression> {
        return this.runner<expression>($$dpth,
            (log) => {
                if (log) {
                    log("expression");
                }
                let $scope$root: Nullable<expression_$0>;
                let $scope$methods: Nullable<expression_$1[]>;
                let $$res: Nullable<expression> = null;
                if (true
                    && this.negate(() => this.matchret($$dpth + 1, $$cr)) !== null
                    && ($scope$root = this.matchexpression_$0($$dpth + 1, $$cr)) !== null
                    && ($scope$methods = this.loop<expression_$1>(() => this.matchexpression_$1($$dpth + 1, $$cr), true)) !== null
                ) {
                    $$res = {kind: ASTKinds.expression, root: $scope$root, methods: $scope$methods};
                }
                return $$res;
            }, $$cr)();
    }
    public matchexpression_$0($$dpth: number, $$cr?: ContextRecorder): Nullable<expression_$0> {
        return this.choice<expression_$0>([
            () => this.matchexpression_$0_1($$dpth + 1, $$cr),
            () => this.matchexpression_$0_2($$dpth + 1, $$cr),
        ]);
    }
    public matchexpression_$0_1($$dpth: number, $$cr?: ContextRecorder): Nullable<expression_$0_1> {
        return this.matchliteral($$dpth + 1, $$cr);
    }
    public matchexpression_$0_2($$dpth: number, $$cr?: ContextRecorder): Nullable<expression_$0_2> {
        return this.matchname($$dpth + 1, $$cr);
    }
    public matchexpression_$1($$dpth: number, $$cr?: ContextRecorder): Nullable<expression_$1> {
        return this.matchmethod($$dpth + 1, $$cr);
    }
    public matchmethod($$dpth: number, $$cr?: ContextRecorder): Nullable<method> {
        return this.runner<method>($$dpth,
            (log) => {
                if (log) {
                    log("method");
                }
                let $scope$method: Nullable<method_$0>;
                let $$res: Nullable<method> = null;
                if (true
                    && ($scope$method = this.matchmethod_$0($$dpth + 1, $$cr)) !== null
                ) {
                    $$res = {kind: ASTKinds.method, method: $scope$method};
                }
                return $$res;
            }, $$cr)();
    }
    public matchmethod_$0($$dpth: number, $$cr?: ContextRecorder): Nullable<method_$0> {
        return this.choice<method_$0>([
            () => this.matchmethod_$0_1($$dpth + 1, $$cr),
            () => this.matchmethod_$0_2($$dpth + 1, $$cr),
        ]);
    }
    public matchmethod_$0_1($$dpth: number, $$cr?: ContextRecorder): Nullable<method_$0_1> {
        return this.matchparameterIndex($$dpth + 1, $$cr);
    }
    public matchmethod_$0_2($$dpth: number, $$cr?: ContextRecorder): Nullable<method_$0_2> {
        return this.matchliteralIndex($$dpth + 1, $$cr);
    }
    public matchparameterIndex($$dpth: number, $$cr?: ContextRecorder): Nullable<parameterIndex> {
        return this.runner<parameterIndex>($$dpth,
            (log) => {
                if (log) {
                    log("parameterIndex");
                }
                let $scope$value: Nullable<parameterIndex_$0>;
                let $$res: Nullable<parameterIndex> = null;
                if (true
                    && this.regexAccept(String.raw`(?:\[)`, $$dpth + 1, $$cr) !== null
                    && this.loop<space>(() => this.matchspace($$dpth + 1, $$cr), true) !== null
                    && ($scope$value = this.matchparameterIndex_$0($$dpth + 1, $$cr)) !== null
                    && this.loop<space>(() => this.matchspace($$dpth + 1, $$cr), true) !== null
                    && this.regexAccept(String.raw`(?:\])`, $$dpth + 1, $$cr) !== null
                ) {
                    $$res = {kind: ASTKinds.parameterIndex, value: $scope$value};
                }
                return $$res;
            }, $$cr)();
    }
    public matchparameterIndex_$0($$dpth: number, $$cr?: ContextRecorder): Nullable<parameterIndex_$0> {
        return this.matchexpression($$dpth + 1, $$cr);
    }
    public matchliteralIndex($$dpth: number, $$cr?: ContextRecorder): Nullable<literalIndex> {
        return this.runner<literalIndex>($$dpth,
            (log) => {
                if (log) {
                    log("literalIndex");
                }
                let $scope$value: Nullable<literalIndex_$0>;
                let $$res: Nullable<literalIndex> = null;
                if (true
                    && this.regexAccept(String.raw`(?:\.)`, $$dpth + 1, $$cr) !== null
                    && ($scope$value = this.matchliteralIndex_$0($$dpth + 1, $$cr)) !== null
                ) {
                    $$res = {kind: ASTKinds.literalIndex, value: $scope$value};
                }
                return $$res;
            }, $$cr)();
    }
    public matchliteralIndex_$0($$dpth: number, $$cr?: ContextRecorder): Nullable<literalIndex_$0> {
        return this.matchname($$dpth + 1, $$cr);
    }
    public matchobjectIndex($$dpth: number, $$cr?: ContextRecorder): Nullable<objectIndex> {
        return this.runner<objectIndex>($$dpth,
            (log) => {
                if (log) {
                    log("objectIndex");
                }
                let $scope$obj: Nullable<expression>;
                let $scope$index: Nullable<objectIndex_$0>;
                let $$res: Nullable<objectIndex> = null;
                if (true
                    && ($scope$obj = this.matchexpression($$dpth + 1, $$cr)) !== null
                    && ($scope$index = this.matchobjectIndex_$0($$dpth + 1, $$cr)) !== null
                ) {
                    $$res = {kind: ASTKinds.objectIndex, obj: $scope$obj, index: $scope$index};
                }
                return $$res;
            }, $$cr)();
    }
    public matchobjectIndex_$0($$dpth: number, $$cr?: ContextRecorder): Nullable<objectIndex_$0> {
        return this.choice<objectIndex_$0>([
            () => this.matchobjectIndex_$0_1($$dpth + 1, $$cr),
            () => this.matchobjectIndex_$0_2($$dpth + 1, $$cr),
        ]);
    }
    public matchobjectIndex_$0_1($$dpth: number, $$cr?: ContextRecorder): Nullable<objectIndex_$0_1> {
        return this.matchparameterIndex($$dpth + 1, $$cr);
    }
    public matchobjectIndex_$0_2($$dpth: number, $$cr?: ContextRecorder): Nullable<objectIndex_$0_2> {
        return this.matchliteralIndex($$dpth + 1, $$cr);
    }
    public matchret($$dpth: number, $$cr?: ContextRecorder): Nullable<ret> {
        return this.runner<ret>($$dpth,
            (log) => {
                if (log) {
                    log("ret");
                }
                let $scope$value: Nullable<Nullable<ret_$0>>;
                let $$res: Nullable<ret> = null;
                if (true
                    && this.regexAccept(String.raw`(?:return(?=\s))`, $$dpth + 1, $$cr) !== null
                    && this.loop<space>(() => this.matchspace($$dpth + 1, $$cr), true) !== null
                    && (($scope$value = this.matchret_$0($$dpth + 1, $$cr)) || true)
                ) {
                    $$res = {kind: ASTKinds.ret, value: $scope$value};
                }
                return $$res;
            }, $$cr)();
    }
    public matchret_$0($$dpth: number, $$cr?: ContextRecorder): Nullable<ret_$0> {
        return this.runner<ret_$0>($$dpth,
            (log) => {
                if (log) {
                    log("ret_$0");
                }
                let $scope$exp: Nullable<expression>;
                let $$res: Nullable<ret_$0> = null;
                if (true
                    && this.regexAccept(String.raw`(?:(?<= ))`, $$dpth + 1, $$cr) !== null
                    && ($scope$exp = this.matchexpression($$dpth + 1, $$cr)) !== null
                ) {
                    $$res = {kind: ASTKinds.ret_$0, exp: $scope$exp};
                }
                return $$res;
            }, $$cr)();
    }
    public matchfunc($$dpth: number, $$cr?: ContextRecorder): Nullable<func> {
        return this.runner<func>($$dpth,
            (log) => {
                if (log) {
                    log("func");
                }
                let $scope$name: Nullable<name>;
                let $scope$args: Nullable<args>;
                let $scope$body: Nullable<executable>;
                let $$res: Nullable<func> = null;
                if (true
                    && this.loop<ws>(() => this.matchws($$dpth + 1, $$cr), true) !== null
                    && this.regexAccept(String.raw`(?:public)`, $$dpth + 1, $$cr) !== null
                    && this.loop<space>(() => this.matchspace($$dpth + 1, $$cr), false) !== null
                    && this.regexAccept(String.raw`(?:function)`, $$dpth + 1, $$cr) !== null
                    && this.loop<space>(() => this.matchspace($$dpth + 1, $$cr), false) !== null
                    && ($scope$name = this.matchname($$dpth + 1, $$cr)) !== null
                    && this.loop<space>(() => this.matchspace($$dpth + 1, $$cr), true) !== null
                    && ($scope$args = this.matchargs($$dpth + 1, $$cr)) !== null
                    && this.loop<ws>(() => this.matchws($$dpth + 1, $$cr), true) !== null
                    && this.regexAccept(String.raw`(?:\{)`, $$dpth + 1, $$cr) !== null
                    && ($scope$body = this.matchexecutable($$dpth + 1, $$cr)) !== null
                    && this.regexAccept(String.raw`(?:\})`, $$dpth + 1, $$cr) !== null
                ) {
                    $$res = {kind: ASTKinds.func, name: $scope$name, args: $scope$args, body: $scope$body};
                }
                return $$res;
            }, $$cr)();
    }
    public matchargs($$dpth: number, $$cr?: ContextRecorder): Nullable<args> {
        return this.runner<args>($$dpth,
            (log) => {
                if (log) {
                    log("args");
                }
                let $scope$leadingArgs: Nullable<args_$0[]>;
                let $scope$lastArg: Nullable<Nullable<args_$1>>;
                let $$res: Nullable<args> = null;
                if (true
                    && this.regexAccept(String.raw`(?:\()`, $$dpth + 1, $$cr) !== null
                    && this.loop<ws>(() => this.matchws($$dpth + 1, $$cr), true) !== null
                    && ($scope$leadingArgs = this.loop<args_$0>(() => this.matchargs_$0($$dpth + 1, $$cr), true)) !== null
                    && this.loop<ws>(() => this.matchws($$dpth + 1, $$cr), true) !== null
                    && (($scope$lastArg = this.matchargs_$1($$dpth + 1, $$cr)) || true)
                    && this.loop<ws>(() => this.matchws($$dpth + 1, $$cr), true) !== null
                    && this.regexAccept(String.raw`(?:\))`, $$dpth + 1, $$cr) !== null
                ) {
                    $$res = {kind: ASTKinds.args, leadingArgs: $scope$leadingArgs, lastArg: $scope$lastArg};
                }
                return $$res;
            }, $$cr)();
    }
    public matchargs_$0($$dpth: number, $$cr?: ContextRecorder): Nullable<args_$0> {
        return this.runner<args_$0>($$dpth,
            (log) => {
                if (log) {
                    log("args_$0");
                }
                let $scope$name: Nullable<name>;
                let $$res: Nullable<args_$0> = null;
                if (true
                    && ($scope$name = this.matchname($$dpth + 1, $$cr)) !== null
                    && this.matchnewLineOrComma($$dpth + 1, $$cr) !== null
                    && this.loop<ws>(() => this.matchws($$dpth + 1, $$cr), true) !== null
                ) {
                    $$res = {kind: ASTKinds.args_$0, name: $scope$name};
                }
                return $$res;
            }, $$cr)();
    }
    public matchargs_$1($$dpth: number, $$cr?: ContextRecorder): Nullable<args_$1> {
        return this.matchname($$dpth + 1, $$cr);
    }
    public matchassignment($$dpth: number, $$cr?: ContextRecorder): Nullable<assignment> {
        return this.runner<assignment>($$dpth,
            (log) => {
                if (log) {
                    log("assignment");
                }
                let $scope$target: Nullable<expression>;
                let $scope$value: Nullable<expression>;
                let $$res: Nullable<assignment> = null;
                if (true
                    && ($scope$target = this.matchexpression($$dpth + 1, $$cr)) !== null
                    && this.loop<space>(() => this.matchspace($$dpth + 1, $$cr), true) !== null
                    && this.matchequals($$dpth + 1, $$cr) !== null
                    && this.loop<space>(() => this.matchspace($$dpth + 1, $$cr), true) !== null
                    && ($scope$value = this.matchexpression($$dpth + 1, $$cr)) !== null
                ) {
                    $$res = {kind: ASTKinds.assignment, target: $scope$target, value: $scope$value};
                }
                return $$res;
            }, $$cr)();
    }
    public test(): boolean {
        const mrk = this.mark();
        const res = this.matchglobals(0);
        const ans = res !== null && this.finished();
        this.reset(mrk);
        return ans;
    }
    public parse(): ParseResult {
        const mrk = this.mark();
        const res = this.matchglobals(0);
        if (res && this.finished()) {
            return new ParseResult(res, null);
        }
        this.reset(mrk);
        const rec = new ErrorTracker();
        this.matchglobals(0, rec);
        return new ParseResult(res,
            rec.getErr() ?? new SyntaxErr(this.mark(), new Set(["$EOF"]), new Set([])));
    }
    public mark(): PosInfo {
        return this.pos;
    }
    private loop<T>(func: $$RuleType<T>, star: boolean = false): Nullable<T[]> {
        const mrk = this.mark();
        const res: T[] = [];
        for (;;) {
            const t = func();
            if (t === null) {
                break;
            }
            res.push(t);
        }
        if (star || res.length > 0) {
            return res;
        }
        this.reset(mrk);
        return null;
    }
    private runner<T>($$dpth: number, fn: $$RuleType<T>, cr?: ContextRecorder): $$RuleType<T> {
        return () => {
            const mrk = this.mark();
            const res = cr ? (() => {
                const extraInfo: string[] = [];
                const result = fn((msg: string) => extraInfo.push(msg));
                cr.record(mrk, $$dpth, result, this.negating, extraInfo);
                return result;
            })() : fn();
            if (res !== null) {
                return res;
            }
            this.reset(mrk);
            return null;
        };
    }
    private choice<T>(fns: Array<$$RuleType<T>>): Nullable<T> {
        for (const f of fns) {
            const res = f();
            if (res !== null) {
                return res;
            }
        }
        return null;
    }
    private regexAccept(match: string, dpth: number, cr?: ContextRecorder): Nullable<string> {
        return this.runner<string>(dpth,
            (log) => {
                if (log) {
                    if (this.negating) {
                        log("$$!StrMatch");
                    } else {
                        log("$$StrMatch");
                    }
                    // We substring from 3 to len - 1 to strip off the
                    // non-capture group syntax added as a WebKit workaround
                    log(match.substring(3, match.length - 1));
                }
                const reg = new RegExp(match, "y");
                reg.lastIndex = this.mark().overallPos;
                const res = reg.exec(this.input);
                if (res) {
                    let lineJmp = 0;
                    let lind = -1;
                    for (let i = 0; i < res[0].length; ++i) {
                        if (res[0][i] === "\n") {
                            ++lineJmp;
                            lind = i;
                        }
                    }
                    this.pos = {
                        overallPos: reg.lastIndex,
                        line: this.pos.line + lineJmp,
                        offset: lind === -1 ? this.pos.offset + res[0].length : (res[0].length - lind - 1)
                    };
                    return res[0];
                }
                return null;
            }, cr)();
    }
    private noConsume<T>(fn: $$RuleType<T>): Nullable<T> {
        const mrk = this.mark();
        const res = fn();
        this.reset(mrk);
        return res;
    }
    private negate<T>(fn: $$RuleType<T>): Nullable<boolean> {
        const mrk = this.mark();
        const oneg = this.negating;
        this.negating = !oneg;
        const res = fn();
        this.negating = oneg;
        this.reset(mrk);
        return res === null ? true : null;
    }
}
export function parse(s: string): ParseResult {
    const p = new Parser(s);
    return p.parse();
}
export class ParseResult {
    public ast: Nullable<globals>;
    public err: Nullable<SyntaxErr>;
    constructor(ast: Nullable<globals>, err: Nullable<SyntaxErr>) {
        this.ast = ast;
        this.err = err;
    }
}
export interface PosInfo {
    readonly overallPos: number;
    readonly line: number;
    readonly offset: number;
}
export class SyntaxErr {
    public pos: PosInfo;
    public exprules: string[];
    public expmatches: string[];
    constructor(pos: PosInfo, exprules: Set<string>, expmatches: Set<string>) {
        this.pos = pos;
        this.exprules = [...exprules];
        this.expmatches = [...expmatches];
    }
    public toString(): string {
        return `Syntax Error at line ${this.pos.line}:${this.pos.offset}. Tried to match rules ${this.exprules.join(", ")}. Expected one of ${this.expmatches.map((x) => ` '${x}'`)}`;
    }
}
class ErrorTracker implements ContextRecorder {
    private mxpos: PosInfo = {overallPos: -1, line: -1, offset: -1};
    private mnd: number = -1;
    private prules: Set<string> = new Set();
    private pmatches: Set<string> = new Set();
    public record(pos: PosInfo, depth: number, result: any, negating: boolean, extraInfo: string[]) {
        if ((result === null) === negating) {
            return;
        }
        if (pos.overallPos > this.mxpos.overallPos) {
            this.mxpos = pos;
            this.mnd = depth;
            this.pmatches.clear();
            this.prules.clear();
        } else if (pos.overallPos === this.mxpos.overallPos && depth < this.mnd) {
            this.mnd = depth;
            this.prules.clear();
        }
        if (this.mxpos.overallPos === pos.overallPos && extraInfo.length >= 2) {
            if (extraInfo[0] === "$$StrMatch") {
                this.pmatches.add(extraInfo[1]);
            }
            if (extraInfo[0] === "$$!StrMatch") {
                this.pmatches.add(`not ${extraInfo[1]}`);
            }
        }
        if (this.mxpos.overallPos === pos.overallPos && this.mnd === depth) {
            extraInfo.forEach((x) => { if (x !== "$$StrMatch" && x !== "$$!StrMatch") { this.prules.add(x); } });
        }
    }
    public getErr(): SyntaxErr | null {
        if (this.mxpos.overallPos !== -1) {
            return new SyntaxErr(this.mxpos, this.prules, this.pmatches);
        }
        return null;
    }
}